version: '3.8'

services:

  postgres_primary:
    image: bitnami/postgresql:17
    container_name: postgres_primary
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=postgres
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - ./primary_data:/bitnami/postgresql
      - ./cowork_backup.dump:/docker-entrypoint-initdb.d/cowork_backup.dump
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh


  postgres_backup_1:
    image: bitnami/postgresql:17
    container_name: postgres_backup_1
    ports:
      - "5433:5432"
    depends_on:
      - postgres_primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_MASTER_HOST=postgres_primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - ./backup1_data:/bitnami/postgresql

  postgres_backup_2:
    image: bitnami/postgresql:17
    container_name: postgres_backup_2
    ports:
      - "5434:5432"
    depends_on:
      - postgres_primary
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_MASTER_HOST=postgres_primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD=replicator_password
    volumes:
      - ./backup2_data:/bitnami/postgresql

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://user:password@postgres_primary:5432/postgres?sslmode=disable
    depends_on:
      - postgres_primary

  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
